### ISSUE TITLE
waiting for connection to event pipe

### ISSUE THREAD

**Issue by samellwood** [cooptex977/isaac-injector#3]
I installed visual studio 13 as suggested and still have this issue, have I done something wrong?

**Comment by omni-** [comment]
Please post a sysinfo dump as well as your .NET Framework version and your Visual C++ Redist version.

Sent from my Windows Phone

**Comment by samellwood** [comment]
Sysinfo:
OS Name Microsoft Windows 7 Home Premium
Version 6.1.7601 Service Pack 1 Build 7601
Other OS Description    Not Available
OS Manufacturer Microsoft Corporation
System Name SAM-PC
System Manufacturer System manufacturer
System Model    System Product Name
System Type x64-based PC
Processor   AMD A10-6800K APU with Radeon(tm) HD Graphics, 4100 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date   American Megatrends Inc. 6102, 5/3/2013
SMBIOS Version  2.7
Windows Directory   C:\Windows
System Directory    C:\Windows\system32
Boot Device \Device\HarddiskVolume1
Locale  United States
Hardware Abstraction Layer  Version = "6.1.7601.17514"
User Name   Sam-PC\Sam
Time Zone   GMT Standard Time
Installed Physical Memory (RAM) 16.0 GB
Total Physical Memory   15.2 GB
Available Physical Memory   11.6 GB
Total Virtual Memory    30.4 GB
Available Virtual Memory    26.3 GB
Page File Space 15.2 GB
Page File   C:\pagefile.sys

.Net framework: v2.0.50727 v3.0 v3.5 v4 v4.0 v4.5.1 

Visual c++ redist version : 12.0.30501

I believe this is what you asked for

**Comment by omni-** [comment]
Yes thank you. It would seem you have everything in order. Can you send me a screenshot of the start poster of visual studio?

Sent from my Windows Phone

**Comment by samellwood** [comment]
Sorry not entirely sure what you mean, do you mean this:
![vs](https://cloud.githubusercontent.com/assets/11018544/6204379/fcb1b902-b540-11e4-92aa-fb1ff5d66af2.png)

**Comment by omni-** [comment]
After it launches

Sent from my Windows Phone

**Comment by samellwood** [comment]
![image](https://cloud.githubusercontent.com/assets/11018544/6204399/897f08f8-b541-11e4-90ef-fc8ae287b62b.png)

**Comment by omni-** [comment]
Do you have much familiarity with programming/working with source?

Sent from my Windows Phone

**Comment by samellwood** [comment]
No sorry :(

**Comment by omni-** [comment]
Well in that case, there isn't much I can do for you... You can try to download the source and build it yourself.

Sent from my Windows Phone

**Comment by samellwood** [comment]
Ah okay, ah well thanks for trying
