### ISSUE TITLE
omni mod loader Isaac-ng.exe stopped working

### ISSUE THREAD

**Issue by kwasny** [cooptex977/isaac-injector#6]
when i'm clicking launch rebirth then i get Isaac-ng.exe stopped working
(i don't have crashlog now idk why)
(sorry for bad eng ;))

**Comment by kwasny** [comment]
can someone help ?

**Comment by omni-** [comment]
Hello kwasny,
I will take a look at this error in the near future. We've not been working on the mod due to directive from Nicalis. We Apologize for the inconvenience.

**Comment by kwasny** [comment]
but u going to work on it ? (in a furture ?) PLS this is only one modloader for tboi:r

**Comment by kwasny** [comment]
hey omni for which one version of isaac is that mod loader (i just need item spawn can u make another program with only item spawner ? I don't need anything else)

**Comment by omni-** [comment]
Sorry for taking so long. It works with the current version of Isaac.
